# Generated by Django 5.0.1 on 2024-01-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of1', models.CharField(blank=True, max_length=30, null=True)),
                ('of2', models.CharField(blank=True, max_length=30, null=True)),
                ('of3', models.CharField(blank=True, max_length=30, null=True)),
                ('of4', models.CharField(blank=True, max_length=30, null=True)),
                ('of5', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
