# Generated by Django 5.0.1 on 2024-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_availableoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableoffers',
            name='of1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='availableoffers',
            name='of2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='availableoffers',
            name='of3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='availableoffers',
            name='of4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='availableoffers',
            name='of5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
