# Generated by Django 5.0.1 on 2024-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_availableoffers_of1_alter_availableoffers_of2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
