# Generated by Django 5.0.1 on 2024-02-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pic',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
